#!/bin/bash

SCRIPTNAME=`basename "$0"`

print_help() {
	cat << EOF
Usage: $SCRIPTNAME filename.tex
Uses 'sleep-until-modified.sh' to watch a given LaTeX file, compiling it and its bibliography when the .tex file is modified.
If the -g/--git flag is used, the program will attempt to create a git commit every 10th modification. Use -gg/--git-immediate to create a commit at every modification.
If the -nc/--no-compile flag is used, the LaTeX and bibliography files will not be compiled. Useful in combination with -g when another program is compiling.
EOF
}

# check dependencies
if ! type sleep-until-modified.sh &>/dev/null ; then
	echo "You are missing the sleep-until-modified.sh dependency. Find it at https://github.com/dave-woods/sleep-until-modified"
	exit 1
fi

do_git=false
no_compile=false
mod_count=9
SLEEPER=sleep-until-modified.sh

# parse_parameters:
while [[ "$1" == -* ]] ; do
	case "$1" in
		-h|-help|--help)
			print_help
			exit
			;;
		-g|--git)
			do_git=true
			echo "Will commit to git."
			shift
			# break
			;;
		-gg|--git-immediate)
			do_git=true
			echo "Will commit to git every save."
			mod_count=0
			shift
			# break
			;;
		-nc|--no-compile)
			no_compile=true
			echo "Will not compile LaTeX files."
			shift
			# break
			;;
		*)
			echo "Invalid parameter: '$1'"
			exit 1
			;;
	esac
done

if [ "$#" != 1 ] ; then
	echo "Incorrect parameters. Use --help for usage instructions."
	exit 1
elif [ "`file --mime-type -b \"$1\"`" != "text/x-tex" ] || [ ${1: -4} != ".tex" ]; then
	echo "File must be a valid LaTeX file. Use --help for usage instructions."
	exit 1
fi

f=${1%.tex}
BIB=$f.aux
TEX=$f.tex

echo "Watching $TEX for changes. Press Ctrl+C to stop."

i=0
while $SLEEPER $TEX;
do
	if [ "$no_compile" = false ] ; then
		echo "Compiling $BIB at $(date)..."
		bibtex $BIB;
		echo "Compiling $TEX at $(date)..."
		pdflatex $TEX;
	fi
	((i++))
	if [ "$do_git" = true ] && (($i > $mod_count));
	then
		git add .;
		git commit -m "Auto-commit: stashing most recent changes.";
		echo "Most recent changes were committed at $(date), but not pushed.";
		((i = 0));
  fi
done
